template_inheritnace/basic_app/urls.py
from django.conf.urls import url

from basic_app import views


app_name = 'basic_app'



urlpatterns = [
    url(r'^relative/$', views.relative,name='relative'),
    url(r'^about/$', views.about,name='about'),
    url(r'^projects/$', views.projects,name='projects'),
    url(r'^skills/$', views.skills,name='skills'),
    url(r'^contact/$', views.contact,name='contact'),
    
]

template_inheritnace/template_inheritnace/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
]

template_inheritnace/basic_app/models.py
from django.db import models

# Create your models here.

template_inheritnace/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'basic_app/index.html')


def about(request):
    return render(request, 'basic_app/about.html')

def projects(request):
    return render(request, 'basic_app/projects.html')    


def skills(request):
    return render(request, 'basic_app/skills.html')


def contact(request):
    return render(request, 'basic_app/contact.html')


def relative(request):
    return render(request, 'basic_app/relative_url_templates.html') 

template_inheritnace/templates/basic_app/about.html
<!DOCTYPE html>

    {% extends "basic_app/base.html" %}
        {% block body_block %} 
        
        <br>
        <div class="container">
            
            <ul class="list-group">
              <li class="list-group-item active"><h4>Education</h4> </li>
              <li class="list-group-item"><h4>Business Adminstration</h4>  managment information system</li>
              <li class="list-group-item"><h4>petrolium</h4>  gas and oil institute</li>
            </ul>
          </div>
        <div class="container">
            
            <ul class="list-group">
              <li class="list-group-item active"><h4>Hobbies</li>
              <li class="list-group-item"><h4>Mathmatic</h4>solving any problem in math when I see it</li>
              <li class="list-group-item"> <h4>Discovering</h4>  of the original and genuine characteristic of the places, tastes and people. <br> Together with this activity goes my interest in the learning of foreign languages,<br> history in particular and    
                One of the most beautiful places I've visited were the Nordic countries with their attitude to the nature,<br> sport, social responsibility and family feelings.     
              </li>
              <li class="list-group-item"><h4>Discovering</h4>  of the original and genuine characteristic of the places, tastes and people. <br> Together with this activity goes my interest in the learning of foreign languages,<br> history in particular and    
              One of the most beautiful places I've visited were the Nordic countries with their attitude to the nature,<br> sport, social responsibility and family feelings.
              </li>
              <li class="list-group-item"><p><h4>Watching Movies </h4>Especially Actions</p></li>
            </ul>
          </div>
        
        
       
        {% endblock %}   

template_inheritnace/templates/basic_app/base.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
<head>
    <title>portfolio</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}"/>

</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <!-- Brand/logo -->
        <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
        
        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:about' %}">ABOUT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:skills' %}">SKILLS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:projects' %}">PROJECTS</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:contact' %}">CONTACT</a>
          </li>
        </ul>
    </nav>
    <div  >
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend -->
        {% endblock %}
    </div>
    
</body>
</html>

template_inheritnace/templates/basic_app/contact.html
<!DOCTYPE html>

    {% extends "basic_app/base.html" %}
        {% block body_block %}    

          
        
        <div class="container" id="contact">
            <h1>Contact</h1>
            
            <div class="w-25 bg-dark text-white" id="mycon"><h3> Ahmad Barho<br> </h3></div><br>
            <div class="w-50 bg-secondary text-white" id="mycon"><h4>Phone :</h4> <h5>957564763</h5></div><br>
            <div class="w-75 bg-secondary text-white" id="mycon"><h4>Email :</h4><h5>ahmad@gmail.com</div><br>
            <div class="w-85 bg-secondary text-white" id="mycon"><h4>Adress :</h4><h5>Bredang alle 48 <br> Stockhom Swedan</h5></div><br>
            
          </div>
        

        {% endblock %}  

template_inheritnace/templates/basic_app/index.html
<!DOCTYPE html>

    {% extends "basic_app/base.html" %}
        {% block body_block %}    
        {% load staticfiles %}

                 
        

        <div class="container-fluid " id="myc" >
             <h1>portfolio</h1>
             <h3>About me:</h3> 
             <div class="row">
               
              <div class="col-sm-3">
                <img class="card-img-top rounded " src="{%static 'images/Ahmad2.jpg'%}" alt="Card image">
              </div>
              
              <div class="col-sm-8">
                <h4 class="card-title ">Ahmad Barho</h4>
                <p class="card-text"><li>business man</li> <li>programmer</li>  </p>                
              </div>
            </div><br>           
              <div class="row">
                <p>I'm a nice fun and friendly person, I'm honest and punctual,
                     I work well in a team but also on my own as I like to set myself goals which I will achieve,
                      I have good listening and communication skills. <br>
                     I have a creative mind and am always up for new challenges.</p>
               
               
              </div>
          </div>

          </div>



        
        
        {% endblock %}     

template_inheritnace/templates/basic_app/projects.html
<!DOCTYPE html>

    {% extends "basic_app/base.html" %}
        {% block body_block %}    

        <h1>WELCOME TO SKILLS</h1>    
        <h2>The PROJECTS could be the projects you have made so far or 
            simply the projects from github (You can use github api for this if you want to challenge your self)</h2>

        {% endblock %}  

template_inheritnace/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>  
    <a href="{% url 'index' %}">LINK TO HOME INDEX</a><br>
    <a href="{% url 'basic_app:about' %}">THE ABOUT PAGE</a><br>
    <a href="{% url 'basic_app:skills' %}">THE SKILLS PAGE</a><br>
    <a href="{% url 'basic_app:projects' %}">THE PROJECTS PAGE</a><br>
    <a href="{% url 'basic_app:contact' %}">THE CONTACT PAGE</a><br>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    
</body>
</html>

template_inheritnace/templates/basic_app/skills.html
<!DOCTYPE html>

    {% extends "basic_app/base.html" %}
        {% block body_block %}    
        
        <div class="container">
        <h1>WELCOME TO SKILLS</h1>             
            <ul class="list-group">
              <li class="list-group-item active"><h4>Skills</h4> </li>
              <li class="list-group-item"><h4>Programming Skills</h4> The skillspages.com website provides resources to support youth employment programs in Massachusetts. 

                The second resource is http://skillspages.com/blog, the Skills Pages Youth Employment Blog, which provides a series of articles about career skills, the job market, summer jobs programs and other topics.</li>
                <li class="list-group-item"><h4>Education Skills</h4> The first is http://skillspages.com/masswbl, which is a set of resource pages with both technical and programmatic information about the Online Work-Based
                     Learning Database and the Massachusetts Work-Based Learning Plan. </li>
                <li class="list-group-item"><h4>Work Skills</h4> The resource pages also provide general information about program design, employer outreach and youth development that is useful to any youth employment and career development program,
                    in Massachusetts or anywhere. These resource pages also include a professional development outline that guide youth
                    program staff and others through a variety of key professional development topics.</li>
            </ul><br>

            <h2>Languages</h2>
                      
            <table class="table">
              <thead>
                <tr>
                  <th>Arabic</th>
                  <th>English</th>
                  <th>Swedish</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Native </td>
                  <td>Fluent</td>
                  <td>good</td>
                </tr>
              </tbody>
            </table>
          </div>

   
        

        {% endblock %}  